### ISSUE TITLE
non-docco style?

### ISSUE THREAD

**Issue by tj** [rstacruz/lidoc#1]
the search / side part looks sweet, will you have theme variants or anything? I find docco's style really painful to read

**Comment by tj** [comment]
oh nvm... looks like it just works with the gross `//` style block comments

**Comment by rstacruz** [comment]
Hello!

Were you looking for a different style of the HTML pages it spits out, or a different format for inline documentation comments?

**Comment by tj** [comment]
both I guess haha, I like the stuff you've added to the output but then I clicked around and saw that it was just using the regular docco stuff which I find much harder to read that say github which displays code normally

**Comment by rstacruz** [comment]
Did you mean that the [source files](https://github.com/rstacruz/lidoc/blob/master/lib/lidoc/models/page.coffee)'s comment style are hard to read, or the [generated documentation](http://ricostacruz.com/lidoc/lib/lidoc/models/page.html)'s visual style?

I know you closed this, but I'm just curious. Thanks for checking it out. :)

**Comment by tj** [comment]
both, it's not a huge deal tho nvm. it looks ok using `#` in coffeescript but `//` in js for that sort of comment looks pretty silly, not something I would adopt
