### ISSUE TITLE
How to get the latest version to get Sass support ?

### ISSUE THREAD

**Issue by MoOx** [rstacruz/lidoc#2]
How can I update the npm package ? I can't ? Did I need to use source ? (I'm a sort of npm noob)

**Comment by rstacruz** [comment]
There's no sass support, sorry. For getting this via NPM, it should just be `npm install -g lidoc` as described [here](http://ricostacruz.com/lidoc/).

**Comment by MoOx** [comment]
No sass support ? What is this... 3eadcea375b8f18672d4a3116ccaa1a435270cc0 ?

**Comment by rstacruz** [comment]
ohhh, that sass support :D

by the way, that's support for documenting Sass files in a project. Let me push that to npm for you right now.

**Comment by MoOx** [comment]
That's what I need. You rock.

**Comment by rstacruz** [comment]
There you go. `npm install -g lidoc` should get you the new version.

**Comment by rstacruz** [comment]
Just curious... what do you use it for? :)

**Comment by MoOx** [comment]
I want to try to create a doc for my repo https://github.com/MoOx/compass-recipes
